name: Sincronizador Automatico del Prode

on:
  schedule:
    # Se ejecuta de forma automática en la nube cada 1 hora
    - cron: '*/15 * * * *'
  workflow_dispatch: # Te permite ejecutarlo a mano desde GitHub si querés forzarlo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-node-version: '18'

      - name: Instalar dependencias de Firebase
        run: npm install firebase

      - name: Ejecutar Robot Sincronizador
        run: node sincronizador.js